In [1]:
import numpy as np

print(np.zeros(13))

jedynka = np.ones(22,dtype=int)

print(jedynka)
print(type(jedynka))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>


In [2]:
j  = [1,1,1,1,1,1]
print(type(j))

u = np.arange(1,2.7E7,3)
print(u)

k = np.linspace(0,10,num=5)
print(k)

<class 'list'>
[1.0000000e+00 4.0000000e+00 7.0000000e+00 ... 2.6999992e+07 2.6999995e+07
 2.6999998e+07]
[ 0.   2.5  5.   7.5 10. ]


In [3]:
l1 = [5,7,8,9]
l2 = [11,34,5,67]
l3 = [12,22,56,89]

l1 = l1+l2+l3
print(l1)

[5, 7, 8, 9, 11, 34, 5, 67, 12, 22, 56, 89]


In [5]:
a = np.array(l1)
b = np.array(l2)
c = np.array(l3)

# a = a+b+c
# print(a)

a = np.concatenate((a,b,c))
print(a)

# CTRL+ /  - narzucenie komentarza na zaznacony blok tekstu lub odkomentowanie
# CTRL + D   duplikacja bloku tekstu

[ 5  7  8  9 11 34  5 67 12 22 56 89 11 34  5 67 12 22 56 89]


In [9]:
listaz1 = [[65,4],[34,56]]

macierzm1 = np.array([[2,99],[78,24]])

print(listaz1)
print(macierzm1)

print(listaz1[0])
print(listaz1[0][1])
# print(listaz1[0,1])

print(macierzm1[0])
print(macierzm1[0][1])
print(macierzm1[0,1])

[[65, 4], [34, 56]]
[[ 2 99]
 [78 24]]
[65, 4]
4
[ 2 99]
99
99
